# CraftTweaker Analysis

This file contains info about the various CraftTweaker scripts that are loaded.
While this information can be used to find things that can be optimized, it
should never used used for a witch hunt. This data is anonymous, and is not
automatically submitted to any online service.

| Script Name                                                    | Time  |
|----------------------------------------------------------------|-------|
| crafttweaker/postInit.zs                                       | 574ms |
| contenttweaker/materials/init.zs                               | 513ms |
| crafttweaker/resources/init.zs                                 | 467ms |
| contenttweaker/blocks.zs                                       | 153ms |
| crafttweaker/prestige.zs                                       | 139ms |
| crafttweaker/modIntegrations/tinkers.zs                        | 91ms  |
| crafttweaker/utils.zs                                          | 88ms  |
| crafttweaker/classes/mods/nuclearCraft.zs                      | 61ms  |
| crafttweaker/classes/mods/appliedEnergistics.zs                | 56ms  |
| crafttweaker/recipes/mods/matterOverdrive.zs                   | 55ms  |
| crafttweaker/recipes/removeAndHide.zs                          | 50ms  |
| crafttweaker/oredict/carpet.zs                                 | 49ms  |
| crafttweaker/recipes/mods/skyOrchards.zs                       | 49ms  |
| crafttweaker/modIntegrations/rustic.zs                         | 44ms  |
| crafttweaker/classes/resources/resource.zs                     | 42ms  |
| crafttweaker/modIntegrations/mekanism.zs                       | 29ms  |
| crafttweaker/modIntegrations/nuclearcraft.zs                   | 28ms  |
| crafttweaker/resources/resources.zs                            | 28ms  |
| crafttweaker/modIntegrations/cyclic.zs                         | 27ms  |
| crafttweaker/modIntegrations/industrialForegoing.zs            | 26ms  |
| contenttweaker/materials/utils.zs                              | 25ms  |
| crafttweaker/staging/containers.zs                             | 23ms  |
| contenttweaker/fluids.zs                                       | 22ms  |
| crafttweaker/resources/resourceHogs.zs                         | 21ms  |
| crafttweaker/recipes/mods/nuclearcraft.zs                      | 20ms  |
| crafttweaker/itemModifiers/tooltips.zs                         | 19ms  |
| crafttweaker/classes/mods/cyclic.zs                            | 18ms  |
| crafttweaker/classes/mods/inspirations.zs                      | 18ms  |
| crafttweaker/modIntegrations/bonsaitrees.zs                    | 18ms  |
| crafttweaker/recipes/mods/tconstruct.zs                        | 17ms  |
| crafttweaker/classes/mods/integratedDynamics.zs                | 16ms  |
| crafttweaker/recipes/mods/tinyProgressions.zs                  | 15ms  |
| contenttweaker/materials/largeScale.zs                         | 14ms  |
| crafttweaker/classes/init.zs                                   | 14ms  |
| crafttweaker/classes/mods/horsePower.zs                        | 13ms  |
| crafttweaker/recipes/mods/deepMobLearning.zs                   | 13ms  |
| crafttweaker/recipes/mods/slabMachines.zs                      | 12ms  |
| crafttweaker/recipes/mods/resourceHogs.zs                      | 12ms  |
| crafttweaker/classes/mods/prestige.zs                          | 12ms  |
| crafttweaker/stages.zs                                         | 12ms  |
| crafttweaker/recipes/removeCategory.zs                         | 12ms  |
| crafttweaker/recipes/mods/thermalFoundation.zs                 | 12ms  |
| crafttweaker/recipes/mods/projecte.zs                          | 12ms  |
| crafttweaker/classes/resources/resourceHogType.zs              | 12ms  |
| crafttweaker/modIntegrations/integratedDynamics.zs             | 12ms  |
| crafttweaker/oredict/leaves.zs                                 | 12ms  |
| crafttweaker/recipes/mods/animalcrops.zs                       | 11ms  |
| crafttweaker/modIntegrations/appliedEnergistics2.zs            | 11ms  |
| crafttweaker/recipes/mods/ironJetpacks.zs                      | 11ms  |
| crafttweaker/classes/mods/astralSorcery.zs                     | 11ms  |
| crafttweaker/classes/utils/recipeUtil.zs                       | 11ms  |
| contenttweaker/postInit.zs                                     | 11ms  |
| crafttweaker/resources/unify.zs                                | 10ms  |
| crafttweaker/recipes/mods/industrialForegoing.zs               | 10ms  |
| crafttweaker/oredict/mods/appliedEnergistics2.zs               | 10ms  |
| crafttweaker/classes/mods/tinkers.zs                           | 9ms   |
| crafttweaker/modIntegrations/practicalLogistics.zs             | 9ms   |
| crafttweaker/recipes/mods/inspirations.zs                      | 9ms   |
| crafttweaker/recipes/mods/xlfoods.zs                           | 9ms   |
| crafttweaker/itemModifiers/hardness.zs                         | 9ms   |
| crafttweaker/recipes/mods/minecraft.zs                         | 8ms   |
| crafttweaker/recipes/mods/rftools.zs                           | 7ms   |
| crafttweaker/craftingUtils.zs                                  | 7ms   |
| crafttweaker/resources/skyOrchards.zs                          | 6ms   |
| crafttweaker/recipes/mods/bdsandm.zs                           | 6ms   |
| crafttweaker/oredict/mods/thermalFoundation.zs                 | 6ms   |
| crafttweaker/recipes/mods/valkyrieLib.zs                       | 6ms   |
| crafttweaker/recipes/mods/appliedEnergistics2.zs               | 6ms   |
| crafttweaker/modIntegrations/inspirations.zs                   | 6ms   |
| crafttweaker/staging/itemsAndRecipes/stages.zs                 | 6ms   |
| contenttweaker/items.zs                                        | 5ms   |
| crafttweaker/recipes/furnace.zs                                | 5ms   |
| crafttweaker/recipes/mods/extraCells.zs                        | 5ms   |
| crafttweaker/classes/utils/unifier.zs                          | 5ms   |
| crafttweaker/oredict/cauldron.zs                               | 5ms   |
| crafttweaker/classes/mods/mekanism.zs                          | 5ms   |
| crafttweaker/recipes/mods/rustic.zs                            | 4ms   |
| crafttweaker/itemModifiers/hide.zs                             | 4ms   |
| crafttweaker/classes/resources/skyOrchardsType.zs              | 4ms   |
| crafttweaker/staging/itemsAndRecipes/items/amberMulch.zs       | 3ms   |
| crafttweaker/recipes/mods/twilightForest.zs                    | 3ms   |
| crafttweaker/recipes/mods/mysticalAgriculture.zs               | 3ms   |
| crafttweaker/preInit.zs                                        | 3ms   |
| crafttweaker/recipes/mods/sonarcore.zs                         | 3ms   |
| crafttweaker/recipes/mods/telepastries.zs                      | 3ms   |
| crafttweaker/recipes/mods/darkutils.zs                         | 3ms   |
| crafttweaker/recipes/mods/iChunUtil.zs                         | 3ms   |
| crafttweaker/recipes/mods/mekanism.zs                          | 3ms   |
| crafttweaker/env.dev.zs                                        | 3ms   |
| crafttweaker/recipes/mods/parabox.zs                           | 3ms   |
| crafttweaker/recipes/mods/astralSorcery.zs                     | 3ms   |
| crafttweaker/recipes/mods/cyclic.zs                            | 2ms   |
| crafttweaker/recipes/mods/clickMachine.zs                      | 2ms   |
| crafttweaker/staging/itemsAndRecipes/modId.zs                  | 2ms   |
| crafttweaker/staging/itemsAndRecipes/items/nonPacifist.zs      | 2ms   |
| crafttweaker/classes/mods/rustic.zs                            | 2ms   |
| crafttweaker/classes/mods/industrialForegoing.zs               | 2ms   |
| crafttweaker/recipes/mods/torchmaster.zs                       | 2ms   |
| crafttweaker/recipes/mods/microblockcbe.zs                     | 2ms   |
| crafttweaker/recipes/mods/statues.zs                           | 2ms   |
| contenttweaker/materials/misc.zs                               | 2ms   |
| crafttweaker/oredict/misc.zs                                   | 2ms   |
| crafttweaker/itemModifiers/rename.zs                           | 2ms   |
| crafttweaker/staging/itemsAndRecipes/items/android.zs          | 2ms   |
| crafttweaker/recipes/mods/chineseworkshop.zs                   | 2ms   |
| crafttweaker/staging/itemsAndRecipes/items/twilightForest.zs   | 2ms   |
| crafttweaker/recipes/mods/cookingForBlockheads.zs              | 2ms   |
| crafttweaker/staging/itemsAndRecipes/items/bonsaiTrees.zs      | 2ms   |
| crafttweaker/staging/tooltips.zs                               | 2ms   |
| crafttweaker/oredict/mods/matteroverdrive.zs                   | 2ms   |
| crafttweaker/staging/itemsAndRecipes/items/mobGrindingUtils.zs | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/orangeSlimeDirt.zs  | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/paraboxTwo.zs       | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/megaTorch.zs        | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/brownMulch.zs       | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/redMulch.zs         | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/blueSlimeDirt.zs    | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/prosperityTree.zs   | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/yellowMulch.zs      | 1ms   |
| crafttweaker/itemModifiers/harvestLevel.zs                     | 1ms   |
| crafttweaker/classes/initUnifier.zs                            | 1ms   |
| crafttweaker/staging/dimensions.zs                             | 1ms   |
| crafttweaker/itemModifiers/burnTime.zs                         | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/smeltery.zs         | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/blueMulch.zs        | 1ms   |
| crafttweaker/env.production.zs                                 | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/fertileSoil.zs      | 1ms   |
| crafttweaker/classes/mods/practicalLogistics.zs                | 1ms   |
| crafttweaker/oredict/mods/industrialForegoing.zs               | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/purpleSlimeDirt.zs  | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/blackMulch.zs       | 1ms   |
| crafttweaker/staging/itemsAndRecipes/items/rubyMulch.zs        | 1ms   |
| crafttweaker/grassSeedDrop.zs                                  | 1ms   |
| crafttweaker/oredict/mods/twilightForest.zs                    | 0ms   |
| crafttweaker/modIntegrations/horsePower.zs                     | 0ms   |
| crafttweaker/recipes/mods/primitiveCrafting.zs                 | 0ms   |
